#!/bin/sh
#
# @name IfoDrone Airframe
#
#
# @class Multirotor
#
# @maintainer Paweł Zawadzki z-essą@gmail.com
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500}

param set SYS_AUTOSTART 49000
param set SYS_AUTOCONFIG 1

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 9
param set-default CA_ROTOR_COUNT 6

# Main motors
param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 0.0
param set-default CA_ROTOR0_PZ 0.1
param set-default CA_ROTOR0_KM 0.5

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY 0.0
param set-default CA_ROTOR1_PZ -0.1
param set-default CA_ROTOR1_KM -0.5

# Side motors (tiltig)
param set-default CA_ROTOR2_TILT 1
param set-default CA_ROTOR2_PX 0
param set-default CA_ROTOR2_PY 0.3
param set-default CA_ROTOR2_KM 0.5

param set-default CA_ROTOR3_TILT 2
param set-default CA_ROTOR3_PX 0
param set-default CA_ROTOR3_PY -0.3
param set-default CA_ROTOR3_KM 0.5

param set-default CA_ROTOR4_TILT 3
param set-default CA_ROTOR4_PX 0.3
param set-default CA_ROTOR4_PY 0
param set-default CA_ROTOR4_KM -0.5

param set-default CA_ROTOR5_TILT 4
param set-default CA_ROTOR5_PX -0.3
param set-default CA_ROTOR5_PY 0
param set-default CA_ROTOR5_KM -0.5

param set ARSP_USE 0
param set FW_ARSP_MODE 0
param set CBRK_AIRSPD_CHK 162128
param set-default ARSP_USE 0
param set-default FW_ARSP_MODE 0
param set-default CBRK_AIRSPD_CHK 162128
param set-default ASPD_DO_CHECKS 0
param set-default ASPD_PRIMARY 0
